env:
  browser: true
  commonjs: true
  es2021: true
plugins:
  - prettier
extends:
  - airbnb-base
  - prettier
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 12
rules: { 'prettier/prettier': 'error' }
