extends:
  - stylelint-config-standard
  - stylelint-config-sass-guidelines
  - stylelint-config-prettier
plugins:
  - stylelint-order
rules:
  order/order: ['custom-properties', 'declarations']
  order/properties-alphabetical-order: true
  no-descending-specificity: null
  selector-attribute-operator-allowed-list: ['=', '*=', '~=']
  selector-class-pattern: null
  selector-max-compound-selectors: 8
  max-nesting-depth: 5
  property-no-vendor-prefix: [true, ignoreProperties: ['mask']]
  scss/at-import-partial-extension-blacklist: null
ignoreFiles:
  - node_modules
