name: CI
on:
  push:
    branches:
      - master

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load node_modules cache
        uses: actions/cache@v2
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{hashFiles('package-lock.json')}}
      - name: Install
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

  Lint:
    runs-on: ubuntu-latest
    needs: Install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load /node_modules/ cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{hashFiles('package-lock.json')}}
      - name: SCSS/CSS Lint
        run: npm run stylelint
      - name: JS Lint
        run: npm run eslint
      - name: Prettier
        run: npm run format

  Build-Minified-CSS:
    runs-on: ubuntu-latest
    needs: [Install, Lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load /node_modules/ cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{hashFiles('package-lock.json')}}
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: minified-css
          path: dist/

  Deploy-Minified-CSS:
    runs-on: ubuntu-latest
    needs: Build-Minified-CSS
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: minified-css
          path: dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
